### ISSUE TITLE
undefined local variable or method `haml_buffer' when using haml templates

### ISSUE THREAD

**Issue by nerdinand** [hanami/view#130]
Steps to reproduce:

1. `hanami new bookshelf --template=haml`
2. `cd bookshelf`
3. `bundle`
4. `hanami generate action web books#new`
5. `hanami server`
6. visit http://localhost:2300/books/new in a browser
7. stack trace is shown: https://gist.github.com/nerdinand/080ebe782ac18bf03d4111e6344e5072

When doing the exact same thing without `--template=haml`, I see an empty page in the browser, as I'd expect.

**Comment by jodosha** [comment]
This is a really subtle bug.

---

In order to render a template, we pass a scope (`Hanami::View::Rendering::Scope`) which wraps the data (locals) that is needed for the rendering process.

This is an object that needs to expose a method for each local that we pass. For instance: if we pass `{ number: 23 }`, if we do `scope.respond_to?(:number) => true` and `scope.number # => 23`. This is a requirement of `tilt`, the low level Ruby gem that we use as rendering engine.

To do this trick we use `#respond_to_missing?` and check if the locals has a corresponding key. If yes, we rely on `#method_missing` to simulate a concrete method.

---

Because we wanted to avoid conflicts between the name of a local and a Ruby's `Object` public methods (which are 57 on MRI 2.4.1), we opted for a custom subclass of `BasicObject`. This class counts a bare minimum set of methods, which reduces the chance of conflict between a locals key, and a public method.

For instance, if we inherit from `Object`, then we can't pass the `{ trust: true }` locals, because `Object` has a method `#trust` that it was going to shadow our data. Whereas `BasicObject` doesn't implement `#trust` and so it doesn't shadow our data.

---

Since `haml` `5.0.0`, there is a requirement of not pass a _frozen_ scope to the HAML engine. This is because it uses `Object#extend` to extend at the runtime the given scope. HAML does this trick to inject `Haml::Helpers` module, which contains `#haml_buffer`.

Now, because our `Hanami::View::Rendering::Scope` is inheriting from `BasicObject` it shouldn't respond to `#extend`, but it does (which is unexpected).

It responds to that method because, it asks the instance variables (`@view` and `@locals`) if the method can be satisfied. Because `@view` is an instance of `Hanami::View` and it implicitly inherit from `Object`, by consequence it respond to `#extend`.

So as result, the `@view` instance is extended by mistake with `Haml::Helpers` (which includes `#haml_buffer). At this point HAML assumes that `#haml_buffer` is present in the context of the scope, but it isn't and it crashes.

**Comment by jodosha** [comment]
@nerdinand Can you please try if it works with this patch? https://github.com/hanami/view/pull/131 Thanks.

**Comment by nerdinand** [comment]
Thanks for the quick fix! Unfortunately it doesn't seem to be quite fixed yet. I'm getting a similar stack trace now while rendering `application.html.haml`: https://gist.github.com/nerdinand/a24df4dca805caee909530b2d091b154

**Comment by jodosha** [comment]
@nerdinand Thanks for the quick feedback. Here's a fix for that too: https://github.com/hanami/view/pull/132

**Comment by nerdinand** [comment]
@jodosha I can confirm, everything works as expected with that fix. Thanks!

**Comment by jodosha** [comment]
@nerdinand Please install `hanami-view-1.0.1` which ships with this fix.
